export const KIRAKIRA_ATTRIBUTES = {
  SESSION_ID: "kirakira.session.id",
  WORKSPACE_ID: "kirakira.workspace.id",
  POLICY_BUNDLE_ID: "kirakira.policy.bundle_id",
  POLICY_DECISION_ID: "kirakira.policy.decision_id",
  APPROVAL_ID: "kirakira.approval.id",
  APPROVAL_SCOPE: "kirakira.approval.scope",
  SANDBOX_PROFILE: "kirakira.sandbox.profile",
  SANDBOX_NETWORK_MODE: "kirakira.sandbox.network_mode",
  MCP_SERVER_ID: "kirakira.mcp.server_id",
  SKILL_ID: "kirakira.skill.id",
  SKILL_VERSION: "kirakira.skill.version",
  REGISTRY_PACKAGE: "kirakira.registry.package",
  REGISTRY_SOURCE: "kirakira.registry.source",
  RISK_LEVEL: "kirakira.risk.level",
  RISK_CLAIMS_COUNT: "kirakira.risk.claims_count",
  AUDIT_EVENT_ID: "kirakira.audit.event_id",
  AUDIT_CHAIN_PREV: "kirakira.audit.chain_prev",
  CAPTURE_CONTENT: "kirakira.capture.content",
} as const;
