// Code generated by scripts/generate-types.ts. DO NOT EDIT.
package types

type PolicyInput struct {
	Version *string `json:"version,omitempty"`
	RequestId string `json:"request_id,omitempty"`
	SessionId string `json:"session_id,omitempty"`
	TraceId string `json:"trace_id,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	Principal map[string]interface{} `json:"principal,omitempty"`
	Workspace map[string]interface{} `json:"workspace,omitempty"`
	Action map[string]interface{} `json:"action,omitempty"`
	Target *map[string]interface{} `json:"target,omitempty"`
	Context *map[string]interface{} `json:"context,omitempty"`
	Risk *map[string]interface{} `json:"risk,omitempty"`
}

type AiriskOutput struct {
	Version *string `json:"version,omitempty"`
	RequestId string `json:"request_id,omitempty"`
	Classification map[string]interface{} `json:"classification,omitempty"`
	Claims []map[string]interface{} `json:"claims,omitempty"`
	RecommendedObligations []string `json:"recommended_obligations,omitempty"`
	CanonicalFingerprintMaterial *map[string]interface{} `json:"canonical_fingerprint_material,omitempty"`
}

type PolicyDecision struct {
	Version *string `json:"version,omitempty"`
	DecisionId string `json:"decision_id,omitempty"`
	RequestId string `json:"request_id,omitempty"`
	Effect string `json:"effect,omitempty"`
	ReasonCodes []string `json:"reason_codes,omitempty"`
	Policy map[string]interface{} `json:"policy,omitempty"`
	Approval map[string]interface{} `json:"approval,omitempty"`
	Obligations []map[string]interface{} `json:"obligations,omitempty"`
	Explain map[string]interface{} `json:"explain,omitempty"`
}

type AuditEvent struct {
	Version *string `json:"version,omitempty"`
	EventId string `json:"event_id,omitempty"`
	Ts string `json:"ts,omitempty"`
	Segment string `json:"segment,omitempty"`
	PrevHash string `json:"prev_hash,omitempty"`
	EntryHash string `json:"entry_hash,omitempty"`
	TraceId string `json:"trace_id,omitempty"`
	DecisionId *string `json:"decision_id,omitempty"`
	Kind string `json:"kind,omitempty"`
	Actor map[string]interface{} `json:"actor,omitempty"`
	Subject map[string]interface{} `json:"subject,omitempty"`
	Result map[string]interface{} `json:"result,omitempty"`
	Metrics *map[string]interface{} `json:"metrics,omitempty"`
	Integrity *map[string]interface{} `json:"integrity,omitempty"`
}

