# Code generated by scripts/generate-types.ts. DO NOT EDIT.
"""Cross-language aligned policy types generated from @kirakira/core Zod schemas."""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

@dataclass
class PolicyInputPrincipal:
    user_id: str = ""
    org_id: Optional[str] = None
    roles: list[str] = field(default_factory=list)
    groups: Optional[list[str]] = None
    authn_method: str = "token"
    device_trust: str = "unknown"
    interactive: bool = True

@dataclass
class PolicyInputWorkspace:
    workspace_id: str = ""
    root: str = ""

@dataclass
class PolicyInputActionNormalized:
    command_ast_hash: Optional[str] = None
    command_base: Optional[str] = None
    flags: list[str] = field(default_factory=list)
    subcommands: list[str] = field(default_factory=list)
    write_paths: list[str] = field(default_factory=list)
    read_paths: list[str] = field(default_factory=list)
    destructive: bool = False
    interpreter_handoff: bool = False
    pipeline_depth: int = 0
    redirection_targets: list[str] = field(default_factory=list)

@dataclass
class PolicyInputAction:
    kind: str = ""
    tool_type: str = ""
    tool_name: str = ""
    operation: str = ""
    normalized: Optional[PolicyInputActionNormalized] = None

@dataclass
class PolicyInput:
    version: str = "kirakira.policyinput.v1"
    request_id: str = ""
    session_id: str = ""
    trace_id: str = ""
    timestamp: str = ""
    principal: PolicyInputPrincipal = field(default_factory=PolicyInputPrincipal)
    workspace: PolicyInputWorkspace = field(default_factory=PolicyInputWorkspace)
    action: PolicyInputAction = field(default_factory=PolicyInputAction)

@dataclass
class PolicyDecisionApproval:
    required: bool = False
    mode: str = "none"
    template_id: Optional[str] = None
    cacheable: bool = False
    ttl_seconds: Optional[int] = None

@dataclass
class Obligation:
    type: str = ""
    profile: Optional[str] = None
    policy: Optional[str] = None
    channel: Optional[str] = None
    required: Optional[bool] = None
    scope: Optional[str] = None
    min_length: Optional[int] = None
    domains: Optional[list[str]] = None

@dataclass
class PolicyDecision:
    version: str = "kirakira.decision.v1"
    decision_id: str = ""
    request_id: str = ""
    effect: str = "deny"
    reason_codes: list[str] = field(default_factory=list)
    obligations: list[Obligation] = field(default_factory=list)

@dataclass
class AuditEvent:
    version: str = "kirakira.audit.v1"
    event_id: str = ""
    ts: str = ""
    segment: str = ""
    prev_hash: str = ""
    entry_hash: str = ""
    trace_id: str = ""
    kind: str = ""
